config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'proponents#index'

  resources :proponents do
    get 'report', on: :collection
  end

  post 'financial/calculate_inss', to: 'financial#calculate_inss'
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :proponent

  validates :street_name, :number, :neighborhood, :city, :state, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_phone.rb
# frozen_string_literal: true

class ContactPhone < ApplicationRecord
  belongs_to :proponent

  validates :number, :contact_type, presence: true
end

app/models/proponent.rb
# frozen_string_literal: true

class Proponent < ApplicationRecord
  has_one :address, dependent: :destroy
  has_many :contact_phones, dependent: :destroy

  validates :name, :cpf, :birthdate, presence: true
  validates :cpf, length: { is: 14 }

  def update(params)
    UpdateWageJob.perform_async(id, params[:wage])

    super(params.except(:wage))
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/financial_controller.rb
# frozen_string_literal: true

class FinancialController < ApplicationController
  skip_before_action :verify_authenticity_token

  def calculate_inss
    inss_discount = Financial::InssDiscountCalculator.call(wage: params[:wage])

    render json: { amount: inss_discount }, status: :ok
  end
end

app/controllers/proponents_controller.rb
# frozen_string_literal: true

class ProponentsController < ApplicationController
  before_action :set_proponent, only: %i[show edit update destroy]

  # GET /proponents or /proponents.json
  def index
    @proponents = Proponent.order(:name).page(params[:page]).per(5)
  end

  # GET /proponents/1 or /proponents/1.json
  def show; end

  # GET /proponents/new
  def new
    @proponent = Proponent.new
  end

  # GET /proponents/1/edit
  def edit; end

  # POST /proponents or /proponents.json
  def create
    @proponent = Proponent.new(proponent_params)

    respond_to do |format|
      if @proponent.save
        format.html { redirect_to proponent_url(@proponent), notice: 'Proponent was successfully created.' }
        format.json { render :show, status: :created, location: @proponent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proponents/1 or /proponents/1.json
  def update
    respond_to do |format|
      if @proponent.update(proponent_params)
        format.html { redirect_to proponent_url(@proponent), notice: 'Proponent was successfully updated.' }
        format.json { render :show, status: :ok, location: @proponent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proponents/1 or /proponents/1.json
  def destroy
    @proponent.destroy

    respond_to do |format|
      format.html { redirect_to proponents_url, notice: 'Proponent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /proponents/report
  def report
    proponents                = Proponent.all
    @proponents_by_wage_range = Proponents::Grouper.by_wage_range(proponents)

    respond_to do |format|
      format.html
      format.json do
        render json: { report_data: @proponents_by_wage_range }, status: :ok
      end
    end
  end

  private

  def set_proponent
    @proponent = Proponent.find(params[:id])
  end

  def proponent_params
    params
      .require(:proponent)
      .permit(
        :name,
        :cpf,
        :birthdate,
        :wage
      )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/proponents_helper.rb
# frozen_string_literal: true

module ProponentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InssDiscount</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proponents/_form.html.erb
<%= form_with(model: proponent) do |form| %>
  <% if proponent.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(proponent.errors.count, "error") %> prohibited this proponent from being saved:</h2>

      <ul>
        <% proponent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div data-controller="financial">
      <%= form.label :wage %>
      <%= form.number_field :wage,
        value: number_to_currency(proponent.wage.to_f, delimiter: "", unit: ""),
        step: :any,
        data: { action: "blur->financial#calculateInss", 'financial-target' => "wage" }
      %>

      <div id="tax">
        <p style="margin: 0px;" data-financial-target="inss">Valor do desconto do INSS: </p>
      </div>
    </div>
    <div>
      <%= form.label :cpf %>
      <%= form.text_field :cpf %>
    </div>
    <div>
      <%= form.label :birthdate %>
      <%= form.date_field :birthdate %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/proponents/_proponent.html.erb
<div id="<%= dom_id proponent %>">
  <ul>
    <li>
      <%= proponent.name %>
    </li>

    <li>
      <%= proponent.cpf %>
    </li>

    <li>
      <%= proponent.birthdate %>
    </li>

    <li>
      <%= proponent.wage %>
    </li>
  </ul>
</div>

app/views/proponents/edit.html.erb
<h1>Editing proponent</h1>

<%= render "form", proponent: @proponent %>

<br>

<div>
  <%= link_to "Show this proponent", @proponent %> |
  <%= link_to "Back to proponents", proponents_path %>
</div>

app/views/proponents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Proponents</h1>

<div id="proponents">
  <% @proponents.each do |proponent| %>
    <%= render proponent %>
    <p>
      <%= link_to "Show this proponent", proponent %>
    </p>
  <% end %>
</div>

<%= link_to "New proponent", new_proponent_path %>
<%= link_to "Report", report_proponents_path %>

<%= paginate @proponents %>

app/views/proponents/new.html.erb
<h1>New proponent</h1>

<%= render "form", proponent: @proponent %>

<br>

<div>
  <%= link_to "Back to proponents", proponents_path %>
</div>

app/views/proponents/report.html.erb
<p style="color: green"><%= notice %></p>

<h1>Porponents Report</h1>

<div id="proponents">
  <% @proponents_by_wage_range.each do |wage_range| %>
    <p>
      <h3>
        <%= wage_range.first.to_s.camelize %>
      </h3>

      <% wage_range.second.each do |proponent| %>
        <%= proponent[:name] %>
        <%= proponent[:cpf] %>
        <br/>
      <% end %>
    </p>
  <% end %>

  <div data-controller="report">
    <canvas id="bar-chart" data-report-target="proponents" width="800" height="450">
    </canvas>
  </div>
</div>

app/views/proponents/show.html.erb
<h2>Proponent details:</h2>

<p style="color: green"><%= notice %></p>

<%= render @proponent %>

<div>
  <%= link_to "Edit this proponent", edit_proponent_path(@proponent) %> |
  <%= link_to "Back to proponents", proponents_path %>

  <%= button_to "Destroy this proponent", @proponent, method: :delete %>
</div>